### ISSUE TITLE
JWT authentication, how does the client-flow work?

### ISSUE THREAD

**Issue by spoetnik** [tag1consulting/building-an-api-with-django#1]
Thanks for your blogpost, and sharing the code in this repo.

I have a question about the flow the client has for authentication.

The JWT_SECRET is unique for each user, and made available via a REST-call

Doe the client, first have to get de JWT_SECRET, and than get the JWT-token? How does the client get the JWT_SECRET?

**Comment by jeremyandrews** [comment]
The client does not ever see the JWT_SECRET. This is only used by the backend when signing the JSON Web Token. Without a per-user JWT_SECRET, a single secret-key is used for all users. If you change that global secret key, all your users are logged out. With a per-user secret key as described in this blog, you're able to change only the per-user secret key and forcibly log out only that user.

In the blogpost, we expose the per-user secret key via a direct database access simply to illustrate what's happening behind the scenes.
